services:
  backend_api:
    image: test_app:ver1.0
    ports: 
      - 8000:8000
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: journal_db
      DATABASE_URL: "postgresql://postgres:postgres@postgres/journal_db"
  
  postgres:
    image: postgres:15
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: journal_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql